name: Say My Name with Cache

on: [push]

jobs:
  say-my-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-deps
          key: cache-ddd469e

      - name: prime-cache-ddd469e
        run: echo Cache status ${{ steps.cache.outputs.cache-hit }}

      - name: Say My Name
        run: echo "Anusha Saha"

